/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rizky Ramadhan
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.FileDialog;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.*;
public class Notepade extends javax.swing.JFrame {
String filename,tampil,lokasi;
private File file;
private boolean saved =true;
    /**
     * Creates new form Notepade
     */
    public Notepade() {
        initComponents();
    }
    public void newfile(){
        if(TeksTulis.getText().equals("")||TeksTulis.getText().equals(tampil)){
            TeksTulis.setText("");
            tampil = "";
            lokasi = "";
            setTitle("NotePade Rizky");
        }else{
            int i = JOptionPane.showConfirmDialog(null, "isi document anda berubah \napakah anda ingin menyimpan perubahan");
            if(i == 0){
                save();
                TeksTulis.setText("");
                tampil = "";
                lokasi = "";
                setTitle("NotePade Rizky");
            }else if(i == 0){
                TeksTulis.setText("");
                tampil = "";
                lokasi = "";
                setTitle("NotePade Rizky");
            }else if(i == 0){
                return;
            }
        }
    }
    public void save(){
        if(file != null){
            FileWriter filewriter = null;
            try {
                filewriter = new FileWriter(file);
                filewriter.write(TeksTulis.getText());
                filewriter.flush();
                saved = true;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "terjadi kesalahan \ntidak dapat di simpan");
            }finally{
                try {
                    filewriter.close();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }else{
            saveAs();
        }
    }
    
    public void saveAs(){
        JFileChooser fg = new JFileChooser(".");
        int i = fg.showSaveDialog(this);
        if(i == JFileChooser.APPROVE_OPTION){
            file = new File(fg.getSelectedFile().getPath() + ".txt");
            setTitle(file.getPath());
            save();
        }
    }
    
    public void open(){
        JFileChooser fg = new JFileChooser();
        fg.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = fg.showSaveDialog(this);
        if(i == fg.CANCEL_OPTION){
            return;
        }
        File bukafile = fg.getSelectedFile();
        if(bukafile == null || bukafile.getName().equals("")){
            JOptionPane.showMessageDialog(this, "pilih sebuah file","EROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            BufferedReader br = new BufferedReader(new FileReader(bukafile));
            StringBuffer sb = new StringBuffer();
            String baris;
            while((baris = br.readLine()) != null){
                sb.append(baris + "\n");
            }
            TeksTulis.setText(sb.toString());
            tampil = TeksTulis.getText();
            lokasi = bukafile.toString();
            setTitle(bukafile.getName()+"- NotePade");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "file tidak di temukan " + ex);
        } catch (IOException ex){
            JOptionPane.showMessageDialog(null, "IO EROR" + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TeksTulis = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuItemNew = new javax.swing.JMenuItem();
        MenuItemOpen = new javax.swing.JMenuItem();
        MenuItemSave = new javax.swing.JMenuItem();
        MenuItemSaveAs = new javax.swing.JMenuItem();
        MenuItemExit = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        MenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi NotePade Rizky Ramadhan");

        TeksTulis.setColumns(20);
        TeksTulis.setRows(5);
        jScrollPane2.setViewportView(TeksTulis);

        MenuFile.setText("File");

        MenuItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemNew.setText("New");
        MenuItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNewActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemNew);

        MenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemOpen.setText("Open");
        MenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemOpenActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemOpen);

        MenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemSave.setText("Save");
        MenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSaveActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemSave);

        MenuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItemSaveAs.setText("Save As....");
        MenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSaveAsActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemSaveAs);

        MenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemExit.setText("Exit");
        MenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuItemExit);

        jMenuBar2.add(MenuFile);

        MenuHelp.setText("Help");

        MenuItemAbout.setText("About");
        MenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAboutActionPerformed(evt);
            }
        });
        MenuHelp.add(MenuItemAbout);

        jMenuBar2.add(MenuHelp);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSaveAsActionPerformed
        // TODO add your handling code here:
        saveAs();
    }//GEN-LAST:event_MenuItemSaveAsActionPerformed

    private void MenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSaveActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_MenuItemSaveActionPerformed

    private void MenuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNewActionPerformed
        // TODO add your handling code here:
        newfile();
    }//GEN-LAST:event_MenuItemNewActionPerformed

    private void MenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemOpenActionPerformed
        // TODO add your handling code here:
        open();
    }//GEN-LAST:event_MenuItemOpenActionPerformed

    private void MenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemExitActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "yakin anda mau keluar nih!","confirmasi lah disini",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuItemExitActionPerformed

    private void MenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aplikasi NotePade ini di buat oleh RIZKY RAMADHAN dengan Menggunakan NetBeans version 8.0");
    }//GEN-LAST:event_MenuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notepade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notepade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notepade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notepade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notepade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenuItem MenuItemAbout;
    private javax.swing.JMenuItem MenuItemExit;
    private javax.swing.JMenuItem MenuItemNew;
    private javax.swing.JMenuItem MenuItemOpen;
    private javax.swing.JMenuItem MenuItemSave;
    private javax.swing.JMenuItem MenuItemSaveAs;
    private javax.swing.JTextArea TeksTulis;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
